[WIP] add geotope_kantone_stand
geoadmin/mf-chsdi3 pull request #3554
Opened 2020-09-28 08:45 UTC by marionb

2020-10-01 12:11 UTC, ltclm commented
@marionb is this pr ready for review or still WIP?

2020-10-02 07:21 UTC, marionb commented
Sorry I forgot to change the title. @ltclm it is ready for a review.

2020-10-02 11:48 UTC, ltclm approved these changes
thank you @marionb 
great work!

2020-10-23 08:42 UTC, marionb commented
This layer has been postponed to the December deploy.

2020-11-24 14:25 UTC, marionb commented
here the new test link: https://mf-chsdi3.dev.bgdi.ch/ltmbr_geotope_kantone_stand/shorten/8d25ffdd6e

2020-11-25 08:30 UTC, b4l requested changes

2020-11-25 08:30 UTC, b4l commented on chsdi/templates/htmlpopup/geotope_kantone_stand.mako
> +<td class="cell-left">${_(layer + 'link')}</td>
There exists a generic link translation that you can use here.

2020-11-26 09:06 UTC, b4l approved these changes

2020-11-26 09:12 UTC, ltclm approved these changes

2020-12-07 15:20 UTC, merged