Ltmbr gletschermaechtigkeit BGDIDIC-1927
geoadmin/mf-chsdi3 pull request #3585
Opened 2020-11-24 20:52 UTC by marionb

test link: https://mf-chsdi3.dev.bgdi.ch/ltmbr_gletschermaechtigkeit_BGDIDIC-1927/shorten/8d2761f5be

2020-11-25 08:54 UTC, b4l approved these changes
Floating point attributes are generally nicer rounded in the tooltip. Otherwise it looks good!

2020-11-25 09:19 UTC, ltclm requested changes
nice work thank you!
concerning technical implementation i have nothing to add.

The only concern i have is the **precision of the attributes**.
Is it really intended to show that precise values? These values have to be rounded i think. But you have to ask the Data owner about that. if not, im really impressed that we're able to measure thinkness with nanometer precision, respect!

2020-11-26 14:42 UTC, marionb commented
@ltclm  The precision is rounding to the nearest whole number. Although there is still a trailing zero in the tool-tip. I could not get rid of it when trying to import the numbers as `Integers` in the model so I am guessing I will have to change the data type in the DB. Not sure if it is really worth it so I left it for the moment.

2020-12-03 12:20 UTC, faselm approved these changes

2020-12-04 07:13 UTC, ltclm requested changes

2020-12-04 07:13 UTC, ltclm commented on chsdi/templates/htmlpopup/gletschermaechtigkeit_gpr_profiles.mako
> +  layer = 'ch.swisstopo.geologie-gletschermaechtigkeit.'
you can use `c['layerBodId']` for the layername

2020-12-04 07:13 UTC, ltclm commented on chsdi/templates/htmlpopup/gletschermaechtigkeit_ice_thikness.mako
> +  layer = 'ch.swisstopo.geologie-gletschermaechtigkeit.'
you can use `c['layerBodId']` for the layername

2020-12-04 08:10 UTC, ltclm requested changes

2020-12-04 08:10 UTC, ltclm commented on chsdi/templates/htmlpopup/gletschermaechtigkeit_ice_thikness.mako
>  <tr><td class="cell-left">${_(layer + 'pk_sgi')}</td> <td>${c['attributes']['pk_sgi'] or '-'}</td></tr>
here you should add the dot

2020-12-04 08:11 UTC, ltclm approved these changes

2020-12-07 15:29 UTC, ltclm commented
@marionb could you please try to resolve the conflicts

2020-12-08 07:56 UTC, closed without merging

2020-12-08 07:57 UTC, rebert commented
rebased and merged here: Ltrea merge gletscher #3592