Adding support for WebMercator with identify_grid function (Windrose)
geoadmin/mf-chsdi3 pull request #3615
Opened 2021-02-02 14:26 UTC by pakb

this is required for https://github.com/geoadmin/web-mapviewer/pull/28 to work properly

2021-02-02 15:48 UTC, procrastinatio requested changes
OK, nice.
* I would merge on `master` on not `data`, so it may be deployed anytime and not on the next data deploy.
* I would also add support for `ESPG:4326`. I know this code is supposed to die very soon, but _soon_ is a very flexible concept
* No tests, are you kidding?

2021-02-02 15:48 UTC, ltclm approved these changes
i have compared the identify results of the these 3 grid layers:
ch.bfe.windenergie-geschwindigkeit_h50 -> source on s3 is epsg:2056
ch.bafu.gewaesserschutz-diffuse_eintraege_phosphor -> source on s3 is epsg:21781
ch.bafu.gewaesserschutz-diffuse_eintraege_stickstoff -> source on s3 is epsg:21781

https://mf-chsdi3.dev.bgdi.ch/ltclm/shorten/8e8ec8dc83
vs
https://s.geo.admin.ch/8e8ec95cb1

seems to work all fine!
Thanky you!!

2021-02-03 08:37 UTC, pakb commented
tests will fail on CI as long as https://github.com/geoadmin/mf-chsdi3/pull/3598 and https://github.com/geoadmin/mf-chsdi3/pull/3613 are not merged on `master`

2021-02-03 12:31 UTC, procrastinatio approved these changes
OK.
Rebase on `master` should fix the tests

2021-02-03 15:35 UTC, rebert approved these changes
nice!

2021-02-04 10:16 UTC, pakb commented
@rebert @ltclm is the `data` branch filled with lots of changes or could we plan a merge with `master` in order to gather the two fixes you made for tests on it?

2021-02-04 10:19 UTC, procrastinatio commented
@pakb it's already in branch `master`. You only have to rebase on `master` and it should be ok.

2021-02-04 10:43 UTC, merged