Update Service Mapbox Vector Tiles
geoadmin/mf-chsdi3 pull request #3630
Opened 2021-02-15 14:41 UTC by davidoesch

Updated according to https://jira.swisstopo.ch/browse/KOGIS_PRJ-1190?focusedCommentId=134160&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-134160

@ltclm  Can you please double check if it corresponds with your structure ?

2021-02-15 14:47 UTC, ltclm requested changes
thank you @davidoesch 
some small changes. rest looks good to me.

2021-02-15 14:47 UTC, ltclm commented on chsdi/static/doc/source/services/sdiservices.rst
> +example of one pbf tile:
this should be titled with ``example of mbtiles download``

2021-02-15 14:47 UTC, ltclm commented on chsdi/static/doc/source/services/sdiservices.rst
> +example of one pbf tile:
or you should change the path to a pbf path:
```
https://vectortiles.geo.admin.ch/tiles/ch.swisstopo.leichte-basiskarte.vt/v1.0.0/1/1/0.pbf
```

2021-02-19 07:38 UTC, rebert commented
@ltclm fine now?

2021-02-19 07:39 UTC, ltclm approved these changes

2021-02-19 10:26 UTC, merged