Update ch.pronatura.waldreservate
geoadmin/mf-chsdi3 pull request #3675
Opened 2021-04-13 13:29 UTC by faselm

2021-04-14 09:46 UTC, b4l commented on chsdi/models/vector/dritte.py
> +    mcpfe_class_rm = Column('mcpfe_class_rm', Unicode)
Why specify rm but in the mako you map rm to de?

2021-04-22 08:56 UTC, ltclm requested changes
thanks for this @faselm.
same here, either remove rm from model and table or fill it with data and remove the mapping.

2021-04-28 12:53 UTC, rebert commented on chsdi/templates/htmlpopup/pronatura.mako
> -    <tr><td class="cell-left">${_('ch.pronatura.waldreservate.name')}</td>                         <td>${c['attributes']['name'] or '-'}</td></tr>
name is the only Declaration that is being translated to rm (NOme)... which is not consistent

2021-04-28 12:54 UTC, rebert requested changes
Nice. Only a translation the rm translation of ch.pronatura.waldreservate.name to adapt

2021-05-02 10:29 UTC, faselm commented
The rm translation has been fixed. However, it seems there are many inconsistencies in the translations for this layer and the bafu one, even on prod. In German, there is "Teilfläche Perimeter [ha]". Unless I'm missing something in German, perimeter in hectars doesn't make sense and the item in translated as "Area" and "Surface in English and French. Also as "Fläche" in rm... Not sure how all this should be fixed. Maybe you have an idea or I will also ask Mario...

2021-05-03 07:01 UTC, ltclm commented
@faselm you can fix the translations in the bod in the table ms_item:
```SQL
select * FROM ms_item where fk_layer_name like '%waldreservate' order by 3,2
```

the translations with for the attribute gisteilobjekt are empty there.

2021-05-03 07:07 UTC, ltclm requested changes
looks good to me.
the attribute mcpfe is obviously not used anymore in chsdi. 
If thats correct, please remove it in this pr from model/mako. Since it is still used in the wms mapfile we will have to keep it in the table.

2021-05-03 07:35 UTC, ltclm commented
you would have to remove it from __queryable_attributes__ too, but please ask mario first.

2021-05-03 08:19 UTC, faselm commented
It's OK for Mario to remove mcpfe

2021-05-03 09:00 UTC, ltclm requested changes

2021-05-03 09:00 UTC, ltclm commented on chsdi/models/vector/dritte.py
> +    __queryable_attributes__ = ['name', 'objnummer', 'gesflaeche', 'gesflaeche', 'gisteilobjekt']
you can remove the whole line from both layers ch.pronatura.waldreservate/ch.bafu.waldreservate, this feature has not been used at all in 2020 and 2021.

2021-05-03 09:26 UTC, ltclm approved these changes

2021-05-03 12:21 UTC, merged