Remove ch.mobility.standorte
geoadmin/mf-chsdi3 pull request #3712
Opened 2021-07-09 13:25 UTC by faselm

2021-07-09 13:26 UTC, b4l approved these changes

2021-07-27 20:14 UTC, b4l approved these changes

2021-08-10 12:50 UTC, ltclm requested changes
there are some tests running with this deprecated layer.
please adapt the tests.
you can run 
`make test`

for the error message

https://github.com/geoadmin/mf-chsdi3/blob/5ba28ee40829de6dfa4cfcca5caa0c6bf96e3251/tests/integration/test_layers_service.py#L218

2021-08-10 13:36 UTC, ltclm approved these changes

2021-09-06 13:19 UTC, merged