Exclude geojson layer from tooltips layer (docu only)
geoadmin/mf-chsdi3 pull request #3815
Opened 2022-03-07 13:50 UTC by procrastinatio

`GeoJSON` have a client-side only tooltip and are hence not callable through the `identify` service. This PR corrects the doc, which is misleading (via `google-group GeoADMIN`)

2022-03-07 14:20 UTC, rebert commented
@procrastinatio there are certain layers where the identify works even though it is a geojson layer. F.ex. ch.bfe.ladestellen-elektromobilitaet ...

2022-03-07 15:15 UTC, rebert commented
@procrastinatio what about a cleanup in bod? set the geojson layers that have no model in chsdi registered to `tooltip=false` ?

2022-03-09 09:12 UTC, rebert requested changes
I will adapt the bod

2022-03-09 11:16 UTC, procrastinatio commented
No, check `mf-geoadmin3` code first. You can't change the value in the BOD, because you have geojson layer with tooltip (most BAFU layers) and geosjon layer without it (most MeteoSchweiz).

2022-03-09 13:14 UTC, rebert commented
@procrastinatio here the exception ch.bfe.ladestationen-elektromobilitaet https://github.com/SFOE/DIEMO-Documentation/blob/master/How%20to%20query%20DIEMO.md

2022-03-09 13:37 UTC, procrastinatio commented
OK, I was wrong `identify`has nothing to to with `tooltips` even if it's also used. We have to refer to `htmlPopup`

2022-03-09 14:04 UTC, rebert approved these changes

2022-03-09 15:33 UTC, merged