Remove field BGDIDIC-342
geoadmin/mf-chsdi3 pull request #3846
Opened 2022-04-01 06:31 UTC by faselm

2022-04-01 15:34 UTC, b4l requested changes

2022-04-01 15:34 UTC, b4l commented on chsdi/templates/htmlpopup/fernwaerme_angebot.mako
> -    <tr><td class="cell-left">${_('ch.bfe.fernwaerme-angebot.heat_supplier_category')}</td>       <td>${c['attributes'][bezeichnung] or '-'}</td></tr>
Remove line 7 as well, thanks!

2022-04-01 15:37 UTC, faselm commented
yep, thanks

2022-04-01 16:07 UTC, b4l commented
@faselm so you want to remove the `bezeichnung_*` in the model as well?

2022-04-04 07:34 UTC, faselm commented
@b4l yes, you're right it has been removed now https://github.com/geoadmin/mf-chsdi3/pull/3846

2022-04-04 07:39 UTC, faselm commented
@b4l should be ok now

2022-04-04 07:51 UTC, b4l approved these changes
@faselm one last dead code line to remove otherwise looking good. Regarding the `bezeichnung_*` attributes, hope this is fine for the customer like this.

2022-04-04 07:51 UTC, b4l commented on chsdi/templates/htmlpopup/fernwaerme_angebot.mako
>      lang = lang if lang in ('fr', 'it','en') else 'de'
Line 6 can be removed as well ;)

2022-04-04 09:49 UTC, merged