BGDIDIC-2352: Removed ch.swisstopo.wanderkarte50_papier.metadata
geoadmin/mf-chsdi3 pull request #3868
Opened 2022-05-05 06:45 UTC by rebert

2022-05-06 06:22 UTC, rebert commented
https://s.geo.admin.ch/651818144503

2022-05-06 12:44 UTC, ltclm requested changes
please remove legends too.

2022-05-13 10:03 UTC, b4l approved these changes
LGTM

2022-05-16 12:45 UTC, ltclm approved these changes
great, thank you!!

2022-05-16 12:53 UTC, merged