BGDIINF_SB-2328: using dev.env in docker-entrypoint.sh
geoadmin/mf-chsdi3 pull request #3888
Opened 2022-05-24 15:26 UTC by hansmannj

Currently in docker-entrypoint.sh rc_dev is sourced. It should be values from dev.env that are used here. And
later on env vars from k8s.

2022-05-25 09:06 UTC, ltshb requested changes

2022-05-25 09:06 UTC, ltshb commented on docker-entrypoint.sh
> +source dev.env
Sourcing environment file in Frankfurt with k8s will not work.

2022-05-25 13:47 UTC, ltshb commented on docker-entrypoint.sh
> +make production.ini development.ini
Very good point to simplify stuff in frankfurt we should avoid using make target when not absolutely needed, usage of `envsubst` is prefered.

2022-05-30 08:22 UTC, hansmannj commented
This PR was meant as a small step towards migration and clean-up and has already been made obsolete by more recent PRs. Hence I'll close it.

2022-05-30 08:22 UTC, closed without merging