PB-974: WIP
geoadmin/mf-chsdi3 pull request #4467
Opened 2024-11-01 15:10 UTC by hansmannj

2024-11-08 10:24 UTC, rebert commented
LGTM. The CI seems not to have the credentials to access OJP 2.0. We should put the new credential to SSM, and update the CI towards this. Maybe we will have to take care about the transition. K8s pods will have to use the new key as well.

2024-11-11 05:44 UTC, ltshb requested changes
Can we easily detect the version of the api.pentransportdata ? if yes we should handle both the old and new version. This way it will make the transition much easier as using the same container with different configuration can be used with both api version.
If not I propose to do it via configuration variable. 
So add two environment variable:
- OPENTRANSPORT_API_URL
- OPENTRANSPORT_API_VERSION

Also we need to make sure that CI uses at least the new version and has the permission for it. But the best practice would be that unit test don't uses the service but mock the service to avoid external data access which can trigger CI failure due to external service failure/unavailibility.

2024-11-11 05:44 UTC, ltshb commented on chsdi/lib/opentransapi/opentransapi.py
> +        self.url = 'https://api.opentransportdata.swiss/ojp20'  # URL of API
Should come from environment variable and not hardcoded here.

2024-11-11 05:44 UTC, ltshb commented on chsdi/lib/opentransapi/opentransapi.py
> +        payload = f"""<?xml version="1.0" encoding="UTF-8"?>
White space should be stripped before sending to the API to save bandwith

2024-11-11 11:09 UTC, hansmannj commented
> Can we easily detect the version of the api.pentransportdata ? if yes we should handle both the old and new version. This way it will make the transition much easier as using the same container with different configuration can be used with both api version. If not I propose to do it via configuration variable. So add two environment variable:
> 
> * OPENTRANSPORT_API_URL
> * OPENTRANSPORT_API_VERSION
> 
> Also we need to make sure that CI uses at least the new version and has the permission for it. But the best practice would be that unit test don't uses the service but mock the service to avoid external data access which can trigger CI failure due to external service failure/unavailibility.

Implemented stripping of whitespaces, taking the URL form the env. Not sure what you mean by version detection.
I think we should only support one version at a time, and we have the control which version we use.
Agreed, we need to be careful when switching.

2024-11-11 11:17 UTC, hansmannj commented on chsdi/lib/opentransapi/opentransapi.py
> +                    <siri:RequestorRef>swisstopo_Abfahrtsmonitor</siri:RequestorRef>
This RequestorRef was suggested by the OJP team

2024-11-12 08:09 UTC, closed without merging